# sc_check() reads a PDF with pdftools (poppler) and runs sc_check_text()
# on the result. The sample PDF ships in inst/extdata/, generated by the
# mother repository's examples/make_sample_paper.py and copied in unchanged.

skip_if_not_installed("pdftools")

kit <- sc_kit()
model <- sc_load_model(kit)

# The Python pipeline's own triples for the same file, taken once from the
# mother repository (PyMuPDF, the default engine):
#   cd statcheck-ml
#   PYTHONIOENCODING=utf-8 <venv python> -m statcheck_ml.cli check \
#     examples/sample_paper_damaged.pdf --json
# (PYTHONPATH=src, because the package was not installed)
#
# results[].{test_type, statistic, verdict}, in order:
#   t     2.45  consistent
#   f     5.10  consistent
#   f     9.20  consistent
#   t     1.80  decision_error
#   t     4.15  consistent
#
# Poppler (pdftools, this port's reader) reads this particular sample the
# same as PyMuPDF: all five triples below match the Python pipeline exactly,
# and so do df1/df2/p_value. That is not guaranteed for every PDF -- the
# mother repository's results/engines.json measured poppler at 0.872 recall
# against 0.911 for pymupdf across the full corpus -- but this small sample
# does not land in that gap, so there is no mismatch to record here.

test_that("sc_check on the damaged sample PDF matches the Python pipeline's triples", {
  path <- system.file("extdata/sample_paper_damaged.pdf", package = "statcheckml")
  got <- sc_check(path, kit, model)

  expect_equal(nrow(got), 5)
  expect_identical(got$test_type, c("t", "f", "f", "t", "t"))
  expect_equal(got$statistic, c(2.45, 5.10, 9.20, 1.80, 4.15), tolerance = 1e-9)
  expect_identical(got$verdict,
                    c("consistent", "consistent", "consistent",
                      "decision_error", "consistent"))

  # Also verified against the Python pipeline's output above.
  expect_equal(got$df1, c(23, 2, 1, 46, 19), tolerance = 1e-9)
  expect_equal(got$df2, c(NA, 30, 118, NA, NA), tolerance = 1e-9)
  expect_equal(got$p_value, c(0.022, 0.012, 0.003, 0.04, 0.001), tolerance = 1e-9)
})

test_that("sc_check adds source_file as the first column", {
  path <- system.file("extdata/sample_paper_damaged.pdf", package = "statcheckml")
  got <- sc_check(path, kit, model)

  expect_identical(names(got)[1], "source_file")
  expect_true(all(got$source_file == path))
})

test_that("sc_check keeps the stages attribute", {
  path <- system.file("extdata/sample_paper_damaged.pdf", package = "statcheckml")
  got <- sc_check(path, kit, model)

  stages <- attr(got, "stages")
  expect_true(stages$windows_kept > 0)
  expect_identical(stages$by_pattern + stages$by_model, nrow(got))
})
